import pandas as pd 
df = pd.read_csv("bank.csv")
print(df)
print(df.head())
print(df.tail())
print(df.columns)
print(df.shape)
print(df.info())
print(df.describe())
print(df["Name"])
print(df.loc[0])
print(df.loc[df["Balance"].idxmax()])
print(df.loc[df["Balance"].idxmin()])
print(df[df["Loan"] > 500000])
print(df.groupby("City")["Customer_ID"].count())
print(df["Balance"].sum())