import pandas as pd 
df=pd.read_csv('weather.csv')
print(df)
print(df.head())
print(df.tail())
print(df.columns)
print(df.shape)
print(df.info())
print(df.describe())
print(df["city"])
print(df.loc[0])
print(df["temperature"].mean())
print(df.loc[df["temperature"].idxmax()])
print(df.loc[df["temperature"].idxmin()])
print(df[df["temperature"] > 35])
print(df.sort_values("rainfall", ascending=False))
print(df.sort_values("rainfall", ascending=True))