import pandas as pd 
df=pd.read_csv('IPL.csv')
print(df)
print(df.head())
print(df.tail())
print(df.columns)
print(df.shape)
print(df.info())
print(df.describe())
print(df["Player"])
print(df.loc[0])
print(df["Runs"].idxmax())
print(df.nlargest(3,"Runs"))
print(df.groupby("Team")["Average"].mean())
print(df.loc[df["Strike Rate"].idxmax()])
print(df.sort_values("Runs", ascending=False))
print(df.sort_values("Runs", ascending=True))
